# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Iron/utils/images/live_wallpaper.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(85, 355, 150, 40))
        self.pushButton.setStyleSheet("\n"
"        QPushButton {\n"
"            background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(0, 100, 255, 255));\n"
"            border-radius: 20px;\n"
"            font: 75 14pt \"MS Shell Dlg 2\";\n"
"            color: white;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgba(0, 130, 255, 255);\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: rgba(0, 80, 255, 255);\n"
"        }\n"
"     ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 355, 150, 40))
        self.pushButton_2.setStyleSheet("\n"
"        QPushButton {\n"
"            background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(0, 100, 255, 255));\n"
"            border-radius: 20px;\n"
"            font: 75 14pt \"MS Shell Dlg 2\";\n"
"            color: white;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgba(0, 130, 255, 255);\n"
"        }\n"
"        QPushButton:pressed {\n"
"            background-color: rgba(0, 80, 255, 255);\n"
"        }\n"
"     ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 80, 400, 40))
        self.textBrowser.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"border-radius:none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 130, 400, 40))
        self.textBrowser_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(50, 180, 400, 200))
        self.textBrowser_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;")
        self.textBrowser_3.setVisible(False)
        self.textBrowser_3.setEnabled(False)
        self.textBrowser_3.setObjectName("textBrowser_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iron"))
        self.pushButton.setText(_translate("MainWindow", "Запустить"))
        self.pushButton_2.setText(_translate("MainWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
